In [ ]:
#This is going to be my revision notebook for Numpy, Pandas, Matplotlib and Seaborn

In [2]:
import numpy as np

In [43]:
#initialising an array
a = np.array(["Akash", "Bhubaneswar", "Bargarh"])
print(a)


['Akash' 'Bhubaneswar' 'Bargarh']


In [18]:
b = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])    #REMEMBER THAT np.array() only takes a single argument
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
#getting to know the dimension of the np array
b.ndim

2

In [12]:
#getting to know the shape of the np array
b.shape

(2, 3)

In [17]:
#finding the data type of the array elements
a.dtype

dtype('<U10')

In [29]:
b[0 , 0:5:2]

array([1, 3, 5])

In [31]:
b[:, 0] = [5,11]
print(b)

[[ 5  2  3  4  5]
 [11  7  8  9 10]]


In [34]:
b[0, 0:4:1] = [5]
print(b)

[[ 5  5  5  5  5]
 [11  7  8  9 10]]


## Question 1
## a) Print the second row
## b) Print all elements > 10
## c) Replace all even numbers with -1


In [51]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

# second_row = arr[1,:]
# print(second_row)
#
# elements = arr[arr > 10]
# print(elements)
#
# arr[arr % 2 == 0] = -1
# print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Question 2
# a) Add a row [10, 10, 10] to `a` using broadcasting
# b) Find column-wise sum (axis=0)
# c) Stack the original and modified arrays vertically

In [55]:
arr = np.array([[ 1 ,2,  3,  4,  5],
                [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

added = arr + np.array([10,10,10,10, 10])

stacked = np.vstack([arr, added])
print(stacked)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
